resources:
  - url: !resource custom-cards/tracker-card.js
    type: js
  - url: !resource custom-cards/vertical-stack-in-card.js
    type: js
  - url: !resource custom-cards/slider-entity-row.js
    type: js

title: Vårt Hem
views:

  - !include home.yaml

  - !include climate.yaml

  - !include lights.yaml

  - !include tv.yaml

  - !include speakers.yaml

  - !include automations.yaml

  - !include batteries.yaml

  - !include systems.yaml
