homeassistant:
  name: Hemma
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

auth:

frontend:
  javascript_version: latest
  themes:
    midnight: !include theme_midnight.yaml

http:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

discovery:

deconz:

mqtt:
  broker: core-mosquitto

history:

logbook:

logger:
  default: warn
  logs:
    custom_components.custom_updater: debug
    pydeconz: debug
    homeassistant.components.deconz: debug

sun:

tts:
  - platform: google

config:

cloud:
  google_actions:
    filter:
      include_entities:
        - light.livingroom_all_window
        - light.livingroom_window_1
        - light.livingroom_window_2
        - light.olivia_ceiling
        - light.olivia_window
        - light.bedroom_window
        - input_boolean.olivia_disco
        - input_boolean.olivia_good_morning
        - input_boolean.olivia_good_night
    entity_config:
      light.livingroom_all_window:
        name: Fönsterlampor
        room: Vardagsrum
      light.livingroom_window_1:
        name: Vänster Fönsterlampa
        room: Vardagsrum
      light.livingroom_window_2:
        name: Höger Fönsterlampa
        room: Vardagsrum
      light.olivia_ceiling:
        name: Taklampa
        aliases:
          - Olivias taklampa
        room: Olivias Rum
      light.olivia_window:
        name: Fönsterlampa
        aliases:
          - Olivias fönsterlampa
        room: Olivias rum
      light.bedroom_window:
        name: Fönsterlampa
        room: Sovrummet
      input_boolean.olivia_good_morning:
        name: Godmorgon Olivia
        room: Olivias rum
      input_boolean.olivia_good_night:
        name: Godnatt Olivia
        room: Olivias rum
      input_boolean.olivia_disco:
        name: Disko Olivia
        room: Olivias rum

device_tracker:

#--------------------------#
# Light Groups              #
#--------------------------#
light: !include groups_lights.yaml

ios:

notify:

custom_updater:
  track:
    - components
    - cards

media_player:
  - platform: kodi
    host: !secret kodi_host
    username: !secret kodi_username
    password: !secret kodi_password

  - platform: xboxone
    device: FD00ADAAD85A091D
    name: Xbox One S

#--------------------------#
# Sensors                  #
#--------------------------#

sensor: !include sensors.yaml

# Weather YWeather
weather:
  - platform: yweather

recorder:
  purge_keep_days: 365
  db_url: !secret recorder_db_url

# Input Boolean Switches
input_boolean:
  livingroom_window_timer:
  bedroom_window_timer:
  olivia_window_timer:
  program_vacation:
  program_winter:
  program_christmas:
  notification_olivia_temperature:
  notification_livingroom_temperature:
  notification_bedroom_temperature:

  #light_states
  light_state_livingroom_window:
  light_state_bedroom_window:
  light_state_bedroom_bureau:
  light_state_bedroom_ceiling:
  light_state_olivia_ceiling:
  light_state_olivia_window:
  light_state_hallway_ceiling:

  # Automations
  olivia_good_morning:
  olivia_good_night:
  olivia_disco:

# Shell Commands
shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'

input_number:
  slider_olivia_temperature_min:
    min: 15
    max: 35
    step: 1

  slider_olivia_temperature_max:
    min: 15
    max: 35
    step: 1

  slider_livingroom_temperature_min:
    min: 15
    max: 35
    step: 1

  slider_livingroom_temperature_max:
    min: 15
    max: 35
    step: 1

  slider_bedroom_temperature_min:
    min: 15
    max: 35
    step: 1

  slider_bedroom_temperature_max:
    min: 15
    max: 35
    step: 1
